//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Forms.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Car", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Car : Forms.ServiceReference1.Machine {
        
        private int PlacesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Forms.ServiceReference1.Engine engineField;
        
        private bool DriveField;
        
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModelField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Places {
            get {
                return this.PlacesField;
            }
            set {
                if ((this.PlacesField.Equals(value) != true)) {
                    this.PlacesField = value;
                    this.RaisePropertyChanged("Places");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public Forms.ServiceReference1.Engine engine {
            get {
                return this.engineField;
            }
            set {
                if ((object.ReferenceEquals(this.engineField, value) != true)) {
                    this.engineField = value;
                    this.RaisePropertyChanged("engine");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public bool Drive {
            get {
                return this.DriveField;
            }
            set {
                if ((this.DriveField.Equals(value) != true)) {
                    this.DriveField = value;
                    this.RaisePropertyChanged("Drive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Model {
            get {
                return this.ModelField;
            }
            set {
                if ((object.ReferenceEquals(this.ModelField, value) != true)) {
                    this.ModelField = value;
                    this.RaisePropertyChanged("Model");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Machine", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Forms.ServiceReference1.Car))]
    public partial class Machine : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MetalField;
        
        private int AgeField;
        
        private bool BreakField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Metal {
            get {
                return this.MetalField;
            }
            set {
                if ((object.ReferenceEquals(this.MetalField, value) != true)) {
                    this.MetalField = value;
                    this.RaisePropertyChanged("Metal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int Age {
            get {
                return this.AgeField;
            }
            set {
                if ((this.AgeField.Equals(value) != true)) {
                    this.AgeField = value;
                    this.RaisePropertyChanged("Age");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public bool Break {
            get {
                return this.BreakField;
            }
            set {
                if ((this.BreakField.Equals(value) != true)) {
                    this.BreakField = value;
                    this.RaisePropertyChanged("Break");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Engine", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Engine : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool WorkField;
        
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string model_engineField;
        
        private int CylindersField;
        
        private int HorsePowerField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool Work {
            get {
                return this.WorkField;
            }
            set {
                if ((this.WorkField.Equals(value) != true)) {
                    this.WorkField = value;
                    this.RaisePropertyChanged("Work");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string model_engine {
            get {
                return this.model_engineField;
            }
            set {
                if ((object.ReferenceEquals(this.model_engineField, value) != true)) {
                    this.model_engineField = value;
                    this.RaisePropertyChanged("model_engine");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int Cylinders {
            get {
                return this.CylindersField;
            }
            set {
                if ((this.CylindersField.Equals(value) != true)) {
                    this.CylindersField = value;
                    this.RaisePropertyChanged("Cylinders");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int HorsePower {
            get {
                return this.HorsePowerField;
            }
            set {
                if ((this.HorsePowerField.Equals(value) != true)) {
                    this.HorsePowerField = value;
                    this.RaisePropertyChanged("HorsePower");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Контракт генерации сообщений с именем metal из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateCars", ReplyAction="*")]
        Forms.ServiceReference1.CreateCarsResponse CreateCars(Forms.ServiceReference1.CreateCarsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateCars", ReplyAction="*")]
        System.Threading.Tasks.Task<Forms.ServiceReference1.CreateCarsResponse> CreateCarsAsync(Forms.ServiceReference1.CreateCarsRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем GetAllCarsResult из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllCars", ReplyAction="*")]
        Forms.ServiceReference1.GetAllCarsResponse GetAllCars(Forms.ServiceReference1.GetAllCarsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllCars", ReplyAction="*")]
        System.Threading.Tasks.Task<Forms.ServiceReference1.GetAllCarsResponse> GetAllCarsAsync(Forms.ServiceReference1.GetAllCarsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateCarsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateCars", Namespace="http://tempuri.org/", Order=0)]
        public Forms.ServiceReference1.CreateCarsRequestBody Body;
        
        public CreateCarsRequest() {
        }
        
        public CreateCarsRequest(Forms.ServiceReference1.CreateCarsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateCarsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string metal;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int age;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string model;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public bool @break;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int places;
        
        public CreateCarsRequestBody() {
        }
        
        public CreateCarsRequestBody(string metal, int age, string model, bool @break, int places) {
            this.metal = metal;
            this.age = age;
            this.model = model;
            this.@break = @break;
            this.places = places;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateCarsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateCarsResponse", Namespace="http://tempuri.org/", Order=0)]
        public Forms.ServiceReference1.CreateCarsResponseBody Body;
        
        public CreateCarsResponse() {
        }
        
        public CreateCarsResponse(Forms.ServiceReference1.CreateCarsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateCarsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int CreateCarsResult;
        
        public CreateCarsResponseBody() {
        }
        
        public CreateCarsResponseBody(int CreateCarsResult) {
            this.CreateCarsResult = CreateCarsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllCarsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllCars", Namespace="http://tempuri.org/", Order=0)]
        public Forms.ServiceReference1.GetAllCarsRequestBody Body;
        
        public GetAllCarsRequest() {
        }
        
        public GetAllCarsRequest(Forms.ServiceReference1.GetAllCarsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllCarsRequestBody {
        
        public GetAllCarsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllCarsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllCarsResponse", Namespace="http://tempuri.org/", Order=0)]
        public Forms.ServiceReference1.GetAllCarsResponseBody Body;
        
        public GetAllCarsResponse() {
        }
        
        public GetAllCarsResponse(Forms.ServiceReference1.GetAllCarsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllCarsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Forms.ServiceReference1.Car[] GetAllCarsResult;
        
        public GetAllCarsResponseBody() {
        }
        
        public GetAllCarsResponseBody(Forms.ServiceReference1.Car[] GetAllCarsResult) {
            this.GetAllCarsResult = GetAllCarsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : Forms.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<Forms.ServiceReference1.WebService1Soap>, Forms.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Forms.ServiceReference1.CreateCarsResponse Forms.ServiceReference1.WebService1Soap.CreateCars(Forms.ServiceReference1.CreateCarsRequest request) {
            return base.Channel.CreateCars(request);
        }
        
        public int CreateCars(string metal, int age, string model, bool @break, int places) {
            Forms.ServiceReference1.CreateCarsRequest inValue = new Forms.ServiceReference1.CreateCarsRequest();
            inValue.Body = new Forms.ServiceReference1.CreateCarsRequestBody();
            inValue.Body.metal = metal;
            inValue.Body.age = age;
            inValue.Body.model = model;
            inValue.Body.@break = @break;
            inValue.Body.places = places;
            Forms.ServiceReference1.CreateCarsResponse retVal = ((Forms.ServiceReference1.WebService1Soap)(this)).CreateCars(inValue);
            return retVal.Body.CreateCarsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Forms.ServiceReference1.CreateCarsResponse> Forms.ServiceReference1.WebService1Soap.CreateCarsAsync(Forms.ServiceReference1.CreateCarsRequest request) {
            return base.Channel.CreateCarsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Forms.ServiceReference1.CreateCarsResponse> CreateCarsAsync(string metal, int age, string model, bool @break, int places) {
            Forms.ServiceReference1.CreateCarsRequest inValue = new Forms.ServiceReference1.CreateCarsRequest();
            inValue.Body = new Forms.ServiceReference1.CreateCarsRequestBody();
            inValue.Body.metal = metal;
            inValue.Body.age = age;
            inValue.Body.model = model;
            inValue.Body.@break = @break;
            inValue.Body.places = places;
            return ((Forms.ServiceReference1.WebService1Soap)(this)).CreateCarsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Forms.ServiceReference1.GetAllCarsResponse Forms.ServiceReference1.WebService1Soap.GetAllCars(Forms.ServiceReference1.GetAllCarsRequest request) {
            return base.Channel.GetAllCars(request);
        }
        
        public Forms.ServiceReference1.Car[] GetAllCars() {
            Forms.ServiceReference1.GetAllCarsRequest inValue = new Forms.ServiceReference1.GetAllCarsRequest();
            inValue.Body = new Forms.ServiceReference1.GetAllCarsRequestBody();
            Forms.ServiceReference1.GetAllCarsResponse retVal = ((Forms.ServiceReference1.WebService1Soap)(this)).GetAllCars(inValue);
            return retVal.Body.GetAllCarsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Forms.ServiceReference1.GetAllCarsResponse> Forms.ServiceReference1.WebService1Soap.GetAllCarsAsync(Forms.ServiceReference1.GetAllCarsRequest request) {
            return base.Channel.GetAllCarsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Forms.ServiceReference1.GetAllCarsResponse> GetAllCarsAsync() {
            Forms.ServiceReference1.GetAllCarsRequest inValue = new Forms.ServiceReference1.GetAllCarsRequest();
            inValue.Body = new Forms.ServiceReference1.GetAllCarsRequestBody();
            return ((Forms.ServiceReference1.WebService1Soap)(this)).GetAllCarsAsync(inValue);
        }
    }
}
